### ISSUE TITLE
Support for log4j.xml configuration?

### ISSUE THREAD

**Issue by dannmartens** [ops4j/org.ops4j.pax.logging#3]
I would like to verify whether there aren't any other methods to configure Pax Logging, beyond the Configuration Admin service.

If not, I would be interested in writing a patch which would introduce support to use log4j.xml to configure logging. If you already have ideas what this patch should include, do not hesitate to share your thoughts.

Thanks for your feedback,
 Dann

**Comment by grgrzybek** [comment]
I know this issue is very old.
pax-logging-log4j2 allows specification of external (xml, yaml, json, properties) file using `org.ops4j.pax.logging.log4j2.config.file` property in `org.ops4j.pax.logging` PID. So still Configuration Admin, but with properties file with only one property.

Same (or even more) with pax-logging-logback - this is the only way to configure Logback, by specifying `org.ops4j.pax.logging.logback.config.file` property in `org.ops4j.pax.logging` PID.

To be honest, I don't plan support for external log4j1.xml file, but feel free (after 9 years) to contribute...
