### ISSUE TITLE
Custom Log levels are getting truncated

### ISSUE THREAD

**Issue by Nirothipan** [ops4j/org.ops4j.pax.logging#55]
```java
 logger.log(Level.getLevel("FLOW_ERROR"), "This is a flow_error level message");
 logger.log(Level.getLevel("FLOW_INFO"), "This is a flow_info level message");
```

Something like above is getting truncated to nearest level in https://github.com/ops4j/org.ops4j.pax.logging/blob/master/pax-logging-api/src/main/java/org/ops4j/pax/logging/log4jv2/Log4jv2Logger.java#L175.L186 while printing the levels. Is there anyway we can print the custom levels

Thanks in Advance

**Comment by Nirothipan** [comment]
@grgrzybek appreciate your inputs on this. Thanks .

**Comment by grgrzybek** [comment]
Hmm, something's wrong with the notifications... I didn't get an email about this one. Sorry!
I'm reviewing the pax-logging issues now.

**Comment by grgrzybek** [comment]
I'm afraid this should be treated as a limitation of Pax Logging.
The main design goals of Pax Logging were/are:
* bring logging facades (like commons-logging or slf4j) into OSGi world - this includes APIs of Log4j1, Log4j2 and Logback
* bridge all the APIs/facades to any of the _backed service_ (namely: Log4j1, Log4j2 and Logback)

So the most important API is `logger.info(message)` (and similar), where you specify the level using method name.

I know there are APIs that allow you to pass custom level to generic `logger.log()` method, but mind that for example behind `org.apache.logging.log4j.Logger.info()` method there may be a ... Log4j1 _backend_.

I know there's org.apache.logging.log4j.Logger#log(org.apache.logging.log4j.Level, ...)` method, but `org.ops4j.pax.logging.log4jv2.Log4jv2Logger#logMessage()` which is eventually called **has to** translate such call into an invocation of `org.ops4j.pax.logging.PaxLogger` interface which (further) does all the OSGi magic and delegate to any _backend_ or even fallback Stdout logger of no _backend_ is found.

That's why your custom logger's _int value_ has to _fit_ between some predefined levels...

**Comment by Nirothipan** [comment]
Thanks for the response.
